# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 06:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HR', max_length=25)),
                ('Head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('designation', models.CharField(max_length=60)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(help_text='Please use the following format: <em>+91__________</em>.', max_length=128)),
                ('department', models.OneToOneField(help_text='Assingn Department (or project to user, The Dept Head defined in Department Table would be the person managing the records of specific employee.', on_delete=django.db.models.deletion.CASCADE, to='operations.Department')),
                ('user', models.OneToOneField(help_text='Create a new user to add as an employee. This would be used as login credentials.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavetype', models.CharField(choices=[(b'medical', b'Medical'), (b'earned', b'Earned'), (b'casual', b'Casual'), (b'excess', b'Excess')], max_length=25, verbose_name='Leave Type')),
                ('status', models.CharField(choices=[(b'pending', b'Pending'), (b'approved', b'Approved'), (b'disapproved', b'Disapproved')], max_length=25)),
                ('reason', models.CharField(default='Casual leave', max_length=400)),
                ('from_date', models.DateField(default=datetime.datetime.now)),
                ('to_date', models.DateField(default=datetime.datetime.now)),
                ('days_of_lave_taken', models.PositiveIntegerField(default=1)),
                ('submit_date', models.DateField(default=datetime.datetime.now)),
                ('available', models.PositiveIntegerField(default=0)),
                ('excess', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Employee')),
            ],
            options={
                'verbose_name': 'Leave Record',
                'verbose_name_plural': 'Leave Records',
            },
        ),
        migrations.CreateModel(
            name='LeavesRemain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavetype', models.CharField(choices=[(b'medical', b'Medical'), (b'earned', b'Earned'), (b'casual', b'Casual'), (b'excess', b'Excess')], max_length=25)),
                ('count', models.PositiveIntegerField(default=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Employee')),
            ],
            options={
                'verbose_name': 'Leave Remain',
                'verbose_name_plural': 'Leave Remains',
            },
        ),
    ]
